#############################################################################
# Makefile for building: NewBalance.app/Contents/MacOS/NewBalance
# Generated by qmake (2.01a) (Qt 4.7.4) on: Sun Mar 18 17:19:59 2012
# Project:  NewBalance.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/local/Qt4.7/mkspecs/macx-g++ -o Makefile NewBalance.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -gdwarf-2 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Qt4.7/mkspecs/macx-g++ -I. -I/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/usr/include/QtCore -I/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/usr/include/QtGui -I/usr/include -I. -F/Library/Frameworks
LINK          = g++
LFLAGS        = -headerpad_max_install_names
LIBS          = $(SUBLIBS) -F/Library/Frameworks -L/Library/Frameworks -framework Patterns -framework Nimble -framework Radiant -framework Valuable -framework Luminous -framework Poetic -framework Resonant -framework Screenplay -framework VideoDisplay -framework MultiTouch -framework Fluffy -framework MultiWidgets -framework ThreadedRendering -lGLEW -framework Cocoa -framework QtGui -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = CustomSliderWidget.cpp \
		ShoeWidget890.cpp \
		ShoeWidget1080.cpp \
		ShoeWidgetRoad.cpp \
		ShoeWidgetTrail.cpp \
		ShoeWidgetAtheletes.cpp \
		FormWidgetPurchase.cpp \
		FormWidgetTry.cpp \
		Global.cpp \
		ImageWithClose.cpp \
		AnimatorWidget.cpp \
		Main.cpp 
OBJECTS       = CustomSliderWidget.o \
		ShoeWidget890.o \
		ShoeWidget1080.o \
		ShoeWidgetRoad.o \
		ShoeWidgetTrail.o \
		ShoeWidgetAtheletes.o \
		FormWidgetPurchase.o \
		FormWidgetTry.o \
		Global.o \
		ImageWithClose.o \
		AnimatorWidget.o \
		Main.o
DIST          = /usr/local/Qt4.7/mkspecs/common/unix.conf \
		/usr/local/Qt4.7/mkspecs/common/mac.conf \
		/usr/local/Qt4.7/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.7/mkspecs/qconfig.pri \
		/usr/local/Qt4.7/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Qt4.7/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.7/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.7/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.7/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.7/mkspecs/features/debug.prf \
		/usr/local/Qt4.7/mkspecs/features/default_post.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.7/mkspecs/features/link_pkgconfig.prf \
		/usr/local/Qt4.7/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.7/mkspecs/features/qt.prf \
		/usr/local/Qt4.7/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.7/mkspecs/features/moc.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.7/mkspecs/features/resources.prf \
		/usr/local/Qt4.7/mkspecs/features/uic.prf \
		/usr/local/Qt4.7/mkspecs/features/yacc.prf \
		/usr/local/Qt4.7/mkspecs/features/lex.prf \
		/usr/local/Qt4.7/mkspecs/features/include_source_dir.prf \
		NewBalance.pro
QMAKE_TARGET  = NewBalance
DESTDIR       = 
TARGET        = NewBalance.app/Contents/MacOS/NewBalance

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile NewBalance.app/Contents/PkgInfo NewBalance.app/Contents/Resources/empty.lproj NewBalance.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) NewBalance.app/Contents/MacOS/ || $(MKDIR) NewBalance.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: NewBalance.pro  /usr/local/Qt4.7/mkspecs/macx-g++/qmake.conf /usr/local/Qt4.7/mkspecs/common/unix.conf \
		/usr/local/Qt4.7/mkspecs/common/mac.conf \
		/usr/local/Qt4.7/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.7/mkspecs/qconfig.pri \
		/usr/local/Qt4.7/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Qt4.7/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.7/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.7/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.7/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.7/mkspecs/features/debug.prf \
		/usr/local/Qt4.7/mkspecs/features/default_post.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.7/mkspecs/features/link_pkgconfig.prf \
		/usr/local/Qt4.7/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.7/mkspecs/features/qt.prf \
		/usr/local/Qt4.7/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.7/mkspecs/features/moc.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.7/mkspecs/features/resources.prf \
		/usr/local/Qt4.7/mkspecs/features/uic.prf \
		/usr/local/Qt4.7/mkspecs/features/yacc.prf \
		/usr/local/Qt4.7/mkspecs/features/lex.prf \
		/usr/local/Qt4.7/mkspecs/features/include_source_dir.prf \
		/Library/Frameworks/QtGui.framework/QtGui.prl \
		/Library/Frameworks/QtCore.framework/QtCore.prl
	$(QMAKE) -spec /usr/local/Qt4.7/mkspecs/macx-g++ -o Makefile NewBalance.pro
/usr/local/Qt4.7/mkspecs/common/unix.conf:
/usr/local/Qt4.7/mkspecs/common/mac.conf:
/usr/local/Qt4.7/mkspecs/common/mac-g++.conf:
/usr/local/Qt4.7/mkspecs/qconfig.pri:
/usr/local/Qt4.7/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Qt4.7/mkspecs/features/qt_functions.prf:
/usr/local/Qt4.7/mkspecs/features/qt_config.prf:
/usr/local/Qt4.7/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt4.7/mkspecs/features/default_pre.prf:
/usr/local/Qt4.7/mkspecs/features/mac/default_pre.prf:
/usr/local/Qt4.7/mkspecs/features/mac/dwarf2.prf:
/usr/local/Qt4.7/mkspecs/features/debug.prf:
/usr/local/Qt4.7/mkspecs/features/default_post.prf:
/usr/local/Qt4.7/mkspecs/features/mac/default_post.prf:
/usr/local/Qt4.7/mkspecs/features/mac/objective_c.prf:
/usr/local/Qt4.7/mkspecs/features/link_pkgconfig.prf:
/usr/local/Qt4.7/mkspecs/features/warn_on.prf:
/usr/local/Qt4.7/mkspecs/features/qt.prf:
/usr/local/Qt4.7/mkspecs/features/unix/thread.prf:
/usr/local/Qt4.7/mkspecs/features/moc.prf:
/usr/local/Qt4.7/mkspecs/features/mac/rez.prf:
/usr/local/Qt4.7/mkspecs/features/mac/sdk.prf:
/usr/local/Qt4.7/mkspecs/features/resources.prf:
/usr/local/Qt4.7/mkspecs/features/uic.prf:
/usr/local/Qt4.7/mkspecs/features/yacc.prf:
/usr/local/Qt4.7/mkspecs/features/lex.prf:
/usr/local/Qt4.7/mkspecs/features/include_source_dir.prf:
/Library/Frameworks/QtGui.framework/QtGui.prl:
/Library/Frameworks/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Qt4.7/mkspecs/macx-g++ -o Makefile NewBalance.pro

NewBalance.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) NewBalance.app/Contents || $(MKDIR) NewBalance.app/Contents 
	@$(DEL_FILE) NewBalance.app/Contents/PkgInfo
	@echo "APPL????" >NewBalance.app/Contents/PkgInfo
NewBalance.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) NewBalance.app/Contents/Resources || $(MKDIR) NewBalance.app/Contents/Resources 
	@touch NewBalance.app/Contents/Resources/empty.lproj
	
NewBalance.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) NewBalance.app/Contents || $(MKDIR) NewBalance.app/Contents 
	@$(DEL_FILE) NewBalance.app/Contents/Info.plist
	@sed -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,NewBalance,g" -e "s,@TYPEINFO@,????,g" /usr/local/Qt4.7/mkspecs/macx-g++/Info.plist.app >NewBalance.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/NewBalance1.0.0 || $(MKDIR) .tmp/NewBalance1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/NewBalance1.0.0/ && $(COPY_FILE) --parents ShoeWidget890.hpp ShoeWidget1080.hpp ShoeWidgetRoad.hpp ShoeWidgetTrail.hpp ShoeWidgetAtheletes.hpp CustomSliderWidget.hpp FormWidgetPurchase.hpp FormWidgetTry.hpp Global.hpp ImageWithClose.hpp AnimatorWidget.hpp .tmp/NewBalance1.0.0/ && $(COPY_FILE) --parents CustomSliderWidget.cpp ShoeWidget890.cpp ShoeWidget1080.cpp ShoeWidgetRoad.cpp ShoeWidgetTrail.cpp ShoeWidgetAtheletes.cpp FormWidgetPurchase.cpp FormWidgetTry.cpp Global.cpp ImageWithClose.cpp AnimatorWidget.cpp Main.cpp .tmp/NewBalance1.0.0/ && (cd `dirname .tmp/NewBalance1.0.0` && $(TAR) NewBalance1.0.0.tar NewBalance1.0.0 && $(COMPRESS) NewBalance1.0.0.tar) && $(MOVE) `dirname .tmp/NewBalance1.0.0`/NewBalance1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/NewBalance1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r NewBalance.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

CustomSliderWidget.o: CustomSliderWidget.cpp CustomSliderWidget.hpp \
		ImageWithClose.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CustomSliderWidget.o CustomSliderWidget.cpp

ShoeWidget890.o: ShoeWidget890.cpp ShoeWidget890.hpp \
		CustomSliderWidget.hpp \
		Global.hpp \
		ImageWithClose.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ShoeWidget890.o ShoeWidget890.cpp

ShoeWidget1080.o: ShoeWidget1080.cpp ShoeWidget1080.hpp \
		CustomSliderWidget.hpp \
		Global.hpp \
		ImageWithClose.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ShoeWidget1080.o ShoeWidget1080.cpp

ShoeWidgetRoad.o: ShoeWidgetRoad.cpp ShoeWidgetRoad.hpp \
		CustomSliderWidget.hpp \
		Global.hpp \
		ImageWithClose.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ShoeWidgetRoad.o ShoeWidgetRoad.cpp

ShoeWidgetTrail.o: ShoeWidgetTrail.cpp ShoeWidgetTrail.hpp \
		CustomSliderWidget.hpp \
		Global.hpp \
		ImageWithClose.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ShoeWidgetTrail.o ShoeWidgetTrail.cpp

ShoeWidgetAtheletes.o: ShoeWidgetAtheletes.cpp ShoeWidgetAtheletes.hpp \
		CustomSliderWidget.hpp \
		Global.hpp \
		ImageWithClose.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ShoeWidgetAtheletes.o ShoeWidgetAtheletes.cpp

FormWidgetPurchase.o: FormWidgetPurchase.cpp FormWidgetPurchase.hpp \
		Global.hpp \
		ImageWithClose.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FormWidgetPurchase.o FormWidgetPurchase.cpp

FormWidgetTry.o: FormWidgetTry.cpp FormWidgetTry.hpp \
		Global.hpp \
		ImageWithClose.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FormWidgetTry.o FormWidgetTry.cpp

Global.o: Global.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Global.o Global.cpp

ImageWithClose.o: ImageWithClose.cpp ImageWithClose.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ImageWithClose.o ImageWithClose.cpp

AnimatorWidget.o: AnimatorWidget.cpp AnimatorWidget.hpp \
		Global.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AnimatorWidget.o AnimatorWidget.cpp

Main.o: Main.cpp CustomSliderWidget.hpp \
		ShoeWidget890.hpp \
		ShoeWidget1080.hpp \
		ShoeWidgetRoad.hpp \
		ShoeWidgetTrail.hpp \
		FormWidgetTry.hpp \
		FormWidgetPurchase.hpp \
		Global.hpp \
		AnimatorWidget.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Main.o Main.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

